AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  whats_up_check

  Sample SAM Template for whats_up_check

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TriggerHealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: triggerhealthchecks/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          SNS_TOPIC: !Ref WhatsUpTopic
      Events:
        TriggerHealthCheck:
          Type: Api
          Properties:
            Method: post
            Path: /up

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: healthcheck/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        SNSTrigger:
          Type: SNS
          Properties:
            Topic:
              Ref: WhatsUpTopic
        # In production we should not have a public
        # API endpoint for this function
        # It is only for testing purposes
        HealthCheck:
          Type: Api
          Properties:
            Method: get
            Path: /health

  WhatsUpTopic:
    Type: AWS::SNS::Topic

Outputs:
  HealthCheckApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/health/"
  HealthCheckFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HealthCheckFunction.Arn
  HealthCheckFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HealthCheckFunctionRole.Arn
